version: 2

updates:
  - package-ecosystem: github-actions
    directory: "/"
    open-pull-requests-limit: 5
    target-branch: main
    schedule:
      interval: weekly
    reviewers:
      - Deuchnord
    commit-message:
      prefix: ci
      include: scope
