title = "Kosmorro"
description = "A program to calculate your ephemerides"
default_language = "en"
base_url = "https://kosmorro.space"

compile_sass = true
minify_html = false

external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true

build_search_index = false

[markdown]
highlight_code = true

[extra]
cli_version = "0.9.0"
lib_version = "0.11.0"

matomo_url = "https://stats.deuchnord.fr/"
matomo_id = 3