title = "Kosmorro"
description = "A program to calculate your ephemerides"
default_language = "en"
base_url = "https://kosmorro.space"

compile_sass = true
minify_html = false

build_search_index = false

[markdown]
highlight_code = true
external_links_target_blank = true

[extra]
cli_version = "0.10.8"
lib_version = "1.0.4"

lib_supported_versions = [
    {number = "1.1", release_date = false, supported = false, killer_version = "1.3", doc = true},
    {number = "1.0", release_date = "2021-11-01", supported = true, killer_version = "1.2", doc = true},
    {number = "0.11", release_date = "2021-04-18", supported = true, killer_version = "1.1", doc = true},
    {number = "0.10", release_date = "2021-04-05", supported = false, killer_version = "1.0", doc = false}
]
