title = "Kosmorro"
description = "A program to calculate your ephemerides"
default_language = "en"
base_url = "https://kosmorro.space"

compile_sass = true
minify_html = false

build_search_index = false

[markdown]
highlight_code = true
external_links_target_blank = true

[extra]
cli_version = "0.10.10"
lib_version = "1.0.6"

lib_supported_versions = [
    {number = "1.1", release_date = false, eol_date = false, doc = true},
    {number = "1.0", release_date = "2021-11-01", eol_date = false, doc = true},
    {number = "0.11", release_date = "2021-04-18", eol_date = false, doc = true},
    {number = "0.10", release_date = "2021-04-05", eol_date = "2021-11-01", doc = false}
]
