on:
  push:
  schedule:
    - cron: 0 0/6 * * *

name: Build and deploy the website

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: Generate pages
        run: |
          make pages

      - name: Build and deploy
        uses: shalzz/zola-deploy-action@v0.14.1
        env:
          PAGES_BRANCH: gh-pages
          TOKEN: ${{ secrets.TOKEN }}
