on:
  push:
    branches: ["main"]
  schedule:
    - cron: 0 0/6 * * *

name: Build and deploy the website

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Prepare Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate API
        run: |
          pip install toml
          make scripts
      
      - name: Generate pages
        run: |
          make pages

      - name: Build and deploy
        uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: gh-pages
          TOKEN: ${{ secrets.TOKEN }}
